//Generated by Selenium IDE

package WebForms;

// import org.junit.Test;
// import org.junit.Before;
// import org.junit.After;
// import static org.junit.Assert.*;

// import static org.hamcrest.CoreMatchers.is;
// import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
// import org.openqa.selenium.remote.RemoteWebDriver;
// import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
// import org.openqa.selenium.support.ui.ExpectedConditions;
// import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class WebFormMain {
	// final static String WEB_FORM_URL = 	"https://www.selenium.dev/selenium/web/web-form.html";
	final static String WEB_FORM_URL = "http://localhost:8584/WebForm2/webform.html";
	
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	public static void main(String[] args) {
		System.out.println("[Selenium] WebFormMain Starting...");
		
		WebFormMain main = new WebFormMain();
		main.setUp();
		main.webFormTest();
		// main.tearDown();
	}
	
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	
	public void tearDown() {
		driver.quit();
	}
	
	public void webFormTest() {
		// driver.get("https://www.selenium.dev/selenium/web/web-form.html");
		driver.get(WEB_FORM_URL);
		driver.manage().window().setSize(new Dimension(1152, 819));
		driver.findElement(By.id("my-text-id")).click();
		driver.findElement(By.id("my-text-id")).sendKeys("ȫ�浿");
		driver.findElement(By.name("my-password")).sendKeys("1234");
		driver.findElement(By.name("my-select")).click();
		{
			WebElement dropdown = driver.findElement(By.name("my-select"));
			dropdown.findElement(By.xpath("//option[. = 'One']")).click();
		}
	    driver.findElement(By.name("my-datalist")).click();
	    driver.findElement(By.name("my-datalist")).sendKeys("Chicago");
	    driver.findElement(By.id("my-check-2")).click();
	    driver.findElement(By.id("my-radio-2")).click();
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.name("my-colors")).sendKeys("#f4450b");
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.cssSelector(".col-md-4:nth-child(3) > .form-label:nth-child(1)")).click();
	    driver.findElement(By.cssSelector(".col-md-4:nth-child(3) > .form-label:nth-child(1)")).click();
	    driver.findElement(By.name("my-colors")).sendKeys("#fb0909");
	    driver.findElement(By.cssSelector(".display-6")).click();
	    driver.findElement(By.name("my-date")).click();
	    driver.findElement(By.cssSelector("tr:nth-child(2) > .day:nth-child(5)")).click();
	    driver.findElement(By.cssSelector(".col-md-4:nth-child(3) > .form-label:nth-child(1)")).click();
	    driver.findElement(By.cssSelector(".flex-shrink-2")).click();
	}

}
