package WebForms;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;

// import static org.hamcrest.CoreMatchers.is;
// import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
// import org.openqa.selenium.remote.RemoteWebDriver;
// import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
// import org.openqa.selenium.support.ui.ExpectedConditions;
// import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class WebFormTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@After
	public void tearDown() {
		// driver.quit();
	}
	
	@Test
	public void webform() {
		driver.get("https://www.selenium.dev/selenium/web/web-form.html");
		driver.manage().window().setSize(new Dimension(945, 1140));
		driver.findElement(By.id("my-text-id")).click();
		driver.findElement(By.id("my-text-id")).sendKeys("안녕하세요");
		driver.findElement(By.name("my-password")).sendKeys("1234");
		driver.findElement(By.name("my-textarea")).sendKeys("이 사이트는 셀레리움을 테스트 하기 위한 페이지 입니다.");
		driver.findElement(By.name("my-colors")).click();
		driver.findElement(By.name("my-colors")).sendKeys("#ff0000");
		driver.findElement(By.cssSelector(".flex-shrink-2")).click();
		driver.findElement(By.name("my-date")).click();
		driver.findElement(By.cssSelector("tr:nth-child(4) > .day:nth-child(4)")).click();
		driver.findElement(By.cssSelector(".d-flex")).click();
		//driver.findElement(By.cssSelector(".btn")).click();
	}
	/*
	@Test
	public void webFormTest() {
		driver.get("https://www.selenium.dev/selenium/web/web-form.html");
		driver.manage().window().setSize(new Dimension(1152, 819));
		driver.findElement(By.id("my-text-id")).click();
		driver.findElement(By.id("my-text-id")).sendKeys("홍길동");
		driver.findElement(By.name("my-password")).sendKeys("1234");
		driver.findElement(By.name("my-select")).click();
		{
			WebElement dropdown = driver.findElement(By.name("my-select"));
			dropdown.findElement(By.xpath("//option[. = 'One']")).click();
		}
	    driver.findElement(By.name("my-datalist")).click();
	    driver.findElement(By.name("my-datalist")).sendKeys("Chicago");
	    driver.findElement(By.id("my-check-2")).click();
	    driver.findElement(By.id("my-radio-2")).click();
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.name("my-colors")).sendKeys("#f4450b");
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.name("my-colors")).click();
	    driver.findElement(By.cssSelector(".col-md-4:nth-child(3) > .form-label:nth-child(1)")).click();
	    driver.findElement(By.cssSelector(".col-md-4:nth-child(3) > .form-label:nth-child(1)")).click();
	    driver.findElement(By.name("my-colors")).sendKeys("#fb0909");
	    driver.findElement(By.cssSelector(".display-6")).click();
	    driver.findElement(By.name("my-date")).click();
	    driver.findElement(By.cssSelector("tr:nth-child(2) > .day:nth-child(5)")).click();
	    driver.findElement(By.cssSelector(".col-md-4:nth-child(3) > .form-label:nth-child(1)")).click();
	    driver.findElement(By.cssSelector(".flex-shrink-2")).click();
	}
	*/
}
